import type { Client, SchemaTypes } from '@datocms/cma-client';
import { match } from 'path-to-regexp';

export const linkableModelApiKeys = [
  'academy_chapter',
  'academy_course',
  'blog_post',
  'changelog_entry',
  'customer_story',
  'doc_group',
  'doc_page',
  'enterprise_app',
  'feature',
  'hosting_app',
  'landing_page',
  'partner',
  'plugin',
  'product_comparison',
  'changelog_entry',
  'showcase_project',
  'success_story',
  'tech_partner',
  'template_demo',
  'use_case_page',
  'user_guides_episode',
  'recipe',
];

export const knownPaths = [
  '/',
  '/404',
  '/academy',
  '/blog',
  '/company/about',
  '/company/brand-assets',
  '/company/profit-sharing',
  '/contact/error',
  '/contact',
  '/contact/thanks',
  '/customer-stories',
  '/customers',
  '/changelog',
  '/docs/community-tutorials',
  '/docs',
  '/enterprise-headless-cms',
  '/features/data-integrity',
  '/features/dynamic-layouts',
  '/features/headless-cms-graphql',
  '/features/headless-cms-multi-language',
  '/features/images-api',
  '/features',
  '/features/real-time-api',
  '/features/structured-content-cms',
  '/features/video-api',
  '/features/workflow-cms',
  '/features/worldwide-cdn',
  '/glossary',
  '/how-to-datocms',
  '/legal/cookie-policy',
  '/legal/gdpr',
  '/legal',
  '/legal/privacy-policy',
  '/legal/terms',
  '/marketplace/enterprise',
  '/marketplace/hosting',
  '/marketplace',
  '/marketplace/plugins/browse',
  '/marketplace/plugins',
  '/marketplace/starters',
  '/partner-program/error',
  '/partner-program',
  '/partner-program/thanks',
  '/partners',
  '/partners/showcase',
  '/pricing',
  '/product-updates',
  '/product',
  '/security',
  '/slack',
  '/slack/thanks',
  '/success-stories',
  '/support/error',
  '/support',
  '/support/thanks',
  '/made-for/best-cms-for-developers',
  '/made-for/cms-digital-marketing',
  '/made-for/content-creators',
  '/tech-partners',
  '/user-guides',
  '/wall',
  '/docs/content-management-api/resources/role/create',
  '/docs/content-management-api/resources/role/update',
  '/docs/content-management-api/resources/role/instances',
  '/docs/content-management-api/resources/role/self',
  '/docs/content-management-api/resources/role/destroy',
  '/docs/content-management-api/resources/user/update',
  '/docs/content-management-api/resources/user/instances',
  '/docs/content-management-api/resources/user/self',
  '/docs/content-management-api/resources/user/me',
  '/docs/content-management-api/resources/user/destroy',
  '/docs/content-management-api/resources/sso-user/instances',
  '/docs/content-management-api/resources/sso-user/self',
  '/docs/content-management-api/resources/sso-user/copy_users',
  '/docs/content-management-api/resources/sso-user/destroy',
  '/docs/content-management-api/resources/audit-log-event/query',
  '/docs/content-management-api/resources/menu-item/create',
  '/docs/content-management-api/resources/menu-item/update',
  '/docs/content-management-api/resources/menu-item/instances',
  '/docs/content-management-api/resources/menu-item/self',
  '/docs/content-management-api/resources/menu-item/destroy',
  '/docs/content-management-api/resources/menu-item/reorder',
  '/docs/content-management-api/resources/schema-menu-item/create',
  '/docs/content-management-api/resources/schema-menu-item/update',
  '/docs/content-management-api/resources/schema-menu-item/instances',
  '/docs/content-management-api/resources/schema-menu-item/self',
  '/docs/content-management-api/resources/schema-menu-item/destroy',
  '/docs/content-management-api/resources/schema-menu-item/reorder',
  '/docs/content-management-api/resources/upload-collection/create',
  '/docs/content-management-api/resources/upload-collection/update',
  '/docs/content-management-api/resources/upload-collection/instances',
  '/docs/content-management-api/resources/upload-collection/self',
  '/docs/content-management-api/resources/upload-collection/destroy',
  '/docs/content-management-api/resources/upload-collection/reorder',
  '/docs/content-management-api/resources/item-type/create',
  '/docs/content-management-api/resources/item-type/update',
  '/docs/content-management-api/resources/item-type/instances',
  '/docs/content-management-api/resources/item-type/self',
  '/docs/content-management-api/resources/item-type/duplicate',
  '/docs/content-management-api/resources/item-type/destroy',
  '/docs/content-management-api/resources/item-type/reorder_fields_and_fieldsets',
  '/docs/content-management-api/resources/field/create',
  '/docs/content-management-api/resources/field/update',
  '/docs/content-management-api/resources/field/instances',
  '/docs/content-management-api/resources/field/referencing',
  '/docs/content-management-api/resources/field/related',
  '/docs/content-management-api/resources/field/self',
  '/docs/content-management-api/resources/field/destroy',
  '/docs/content-management-api/resources/field/duplicate',
  '/docs/content-management-api/resources/fieldset/create',
  '/docs/content-management-api/resources/fieldset/update',
  '/docs/content-management-api/resources/fieldset/instances',
  '/docs/content-management-api/resources/fieldset/self',
  '/docs/content-management-api/resources/fieldset/destroy',
  '/docs/content-management-api/resources/session/create',
  '/docs/content-management-api/resources/access-token/create',
  '/docs/content-management-api/resources/access-token/update',
  '/docs/content-management-api/resources/access-token/instances',
  '/docs/content-management-api/resources/access-token/self',
  '/docs/content-management-api/resources/access-token/regenerate_token',
  '/docs/content-management-api/resources/access-token/destroy',
  '/docs/content-management-api/resources/plugin/create',
  '/docs/content-management-api/resources/plugin/update',
  '/docs/content-management-api/resources/plugin/instances',
  '/docs/content-management-api/resources/plugin/self',
  '/docs/content-management-api/resources/plugin/destroy',
  '/docs/content-management-api/resources/plugin/fields',
  '/docs/content-management-api/resources/job-result/self',
  '/docs/content-management-api/resources/subscription-limit/instances',
  '/docs/content-management-api/resources/subscription-limit/self',
  '/docs/content-management-api/resources/subscription-feature/instances',
  '/docs/content-management-api/resources/build-event/instances',
  '/docs/content-management-api/resources/build-event/self',
  '/docs/content-management-api/resources/item/instances',
  '/docs/content-management-api/resources/item/validate_existing',
  '/docs/content-management-api/resources/item/validate_new',
  '/docs/content-management-api/resources/item/create',
  '/docs/content-management-api/resources/item/duplicate',
  '/docs/content-management-api/resources/item/update',
  '/docs/content-management-api/resources/item/references',
  '/docs/content-management-api/resources/item/self',
  '/docs/content-management-api/resources/item/current_vs_published_state',
  '/docs/content-management-api/resources/item/destroy',
  '/docs/content-management-api/resources/item/batch_destroy',
  '/docs/content-management-api/resources/item/batch_publish',
  '/docs/content-management-api/resources/item/batch_unpublish',
  '/docs/content-management-api/resources/item/publish',
  '/docs/content-management-api/resources/item/unpublish',
  '/docs/content-management-api/resources/item/bulk_publish',
  '/docs/content-management-api/resources/item/bulk_unpublish',
  '/docs/content-management-api/resources/item/bulk_destroy',
  '/docs/content-management-api/resources/item/bulk_move_to_stage',
  '/docs/content-management-api/resources/item-version/restore',
  '/docs/content-management-api/resources/item-version/instances',
  '/docs/content-management-api/resources/item-version/self',
  '/docs/content-management-api/resources/upload/create',
  '/docs/content-management-api/resources/upload/instances',
  '/docs/content-management-api/resources/upload/self',
  '/docs/content-management-api/resources/upload/destroy',
  '/docs/content-management-api/resources/upload/update',
  '/docs/content-management-api/resources/upload/batch_add_tags',
  '/docs/content-management-api/resources/upload/batch_destroy',
  '/docs/content-management-api/resources/upload/references',
  '/docs/content-management-api/resources/upload/bulk_tag',
  '/docs/content-management-api/resources/upload/bulk_set_upload_collection',
  '/docs/content-management-api/resources/upload/bulk_destroy',
  '/docs/content-management-api/resources/upload-request/create',
  '/docs/content-management-api/resources/upload-track/create',
  '/docs/content-management-api/resources/upload-track/instances',
  '/docs/content-management-api/resources/upload-track/destroy',
  '/docs/content-management-api/resources/upload-track/generate_subtitles',
  '/docs/content-management-api/resources/scheduled-publication/create',
  '/docs/content-management-api/resources/scheduled-publication/destroy',
  '/docs/content-management-api/resources/scheduled-unpublishing/create',
  '/docs/content-management-api/resources/scheduled-unpublishing/destroy',
  '/docs/content-management-api/resources/search-result/instances',
  '/docs/content-management-api/resources/environment/fork',
  '/docs/content-management-api/resources/environment/promote',
  '/docs/content-management-api/resources/environment/rename',
  '/docs/content-management-api/resources/environment/instances',
  '/docs/content-management-api/resources/environment/self',
  '/docs/content-management-api/resources/environment/destroy',
  '/docs/content-management-api/resources/maintenance-mode/self',
  '/docs/content-management-api/resources/maintenance-mode/activate',
  '/docs/content-management-api/resources/maintenance-mode/deactivate',
  '/docs/content-management-api/resources/webhook/create',
  '/docs/content-management-api/resources/webhook/update',
  '/docs/content-management-api/resources/webhook/instances',
  '/docs/content-management-api/resources/webhook/self',
  '/docs/content-management-api/resources/webhook/destroy',
  '/docs/content-management-api/resources/webhook-call/instances',
  '/docs/content-management-api/resources/webhook-call/self',
  '/docs/content-management-api/resources/webhook-call/resend_webhook',
  '/docs/content-management-api/resources/build-trigger/instances',
  '/docs/content-management-api/resources/build-trigger/self',
  '/docs/content-management-api/resources/build-trigger/create',
  '/docs/content-management-api/resources/build-trigger/update',
  '/docs/content-management-api/resources/build-trigger/trigger',
  '/docs/content-management-api/resources/build-trigger/abort',
  '/docs/content-management-api/resources/build-trigger/abort_indexing',
  '/docs/content-management-api/resources/build-trigger/reindex',
  '/docs/content-management-api/resources/build-trigger/destroy',
  '/docs/content-management-api/resources/item-type-filter/create',
  '/docs/content-management-api/resources/item-type-filter/update',
  '/docs/content-management-api/resources/item-type-filter/instances',
  '/docs/content-management-api/resources/item-type-filter/self',
  '/docs/content-management-api/resources/item-type-filter/destroy',
  '/docs/content-management-api/resources/upload-filter/create',
  '/docs/content-management-api/resources/upload-filter/update',
  '/docs/content-management-api/resources/upload-filter/instances',
  '/docs/content-management-api/resources/upload-filter/self',
  '/docs/content-management-api/resources/upload-filter/destroy',
  '/docs/content-management-api/resources/site-invitation/create',
  '/docs/content-management-api/resources/site-invitation/update',
  '/docs/content-management-api/resources/site-invitation/instances',
  '/docs/content-management-api/resources/site-invitation/self',
  '/docs/content-management-api/resources/site-invitation/destroy',
  '/docs/content-management-api/resources/site-invitation/resend',
  '/docs/content-management-api/resources/editing-session/instances',
  '/docs/content-management-api/resources/editing-session/update',
  '/docs/content-management-api/resources/editing-session/destroy',
  '/docs/content-management-api/resources/sso-group/instances',
  '/docs/content-management-api/resources/sso-group/copy_roles',
  '/docs/content-management-api/resources/sso-group/update',
  '/docs/content-management-api/resources/sso-group/destroy',
  '/docs/content-management-api/resources/sso-settings/self',
  '/docs/content-management-api/resources/sso-settings/generate_token',
  '/docs/content-management-api/resources/sso-settings/update',
  '/docs/content-management-api/resources/emoji-suggestions/self',
  '/docs/content-management-api/resources/white-label-settings/self',
  '/docs/content-management-api/resources/white-label-settings/update',
  '/docs/content-management-api/resources/public-info/self',
  '/docs/content-management-api/resources/daily-usage/instances',
  '/docs/content-management-api/resources/usage-counter/self',
  '/docs/content-management-api/resources/upload-tag/instances',
  '/docs/content-management-api/resources/upload-tag/create',
  '/docs/content-management-api/resources/upload-smart-tag/instances',
  '/docs/content-management-api/resources/site/self',
  '/docs/content-management-api/resources/site/update',
  '/docs/content-management-api/resources/site/activate_improved_timezone_management',
  '/docs/content-management-api/resources/site/activate_improved_hex_management',
  '/docs/content-management-api/resources/site/activate_improved_gql_multilocale_fields',
  '/docs/content-management-api/resources/site/activate_improved_gql_visibility_control',
  '/docs/content-management-api/resources/site/activate_improved_boolean_fields',
  '/docs/content-management-api/resources/site/update_assets_cdn_default_settings',
  '/docs/content-management-api/resources/workflow/create',
  '/docs/content-management-api/resources/workflow/update',
  '/docs/content-management-api/resources/workflow/instances',
  '/docs/content-management-api/resources/workflow/self',
  '/docs/content-management-api/resources/workflow/destroy',
  '/docs/content-management-api/resources/role',
  '/docs/content-management-api/resources/user',
  '/docs/content-management-api/resources/sso-user',
  '/docs/content-management-api/resources/audit-log-event',
  '/docs/content-management-api/resources/account',
  '/docs/content-management-api/resources/organization',
  '/docs/content-management-api/resources/site-plan',
  '/docs/content-management-api/resources/menu-item',
  '/docs/content-management-api/resources/schema-menu-item',
  '/docs/content-management-api/resources/upload-collection',
  '/docs/content-management-api/resources/item-type',
  '/docs/content-management-api/resources/field',
  '/docs/content-management-api/resources/fieldset',
  '/docs/content-management-api/resources/job',
  '/docs/content-management-api/resources/session',
  '/docs/content-management-api/resources/access-token',
  '/docs/content-management-api/resources/plugin',
  '/docs/content-management-api/resources/job-result',
  '/docs/content-management-api/resources/subscription-limit',
  '/docs/content-management-api/resources/subscription-feature',
  '/docs/content-management-api/resources/build-event',
  '/docs/content-management-api/resources/item',
  '/docs/content-management-api/resources/item-current-vs-published-state',
  '/docs/content-management-api/resources/item-version',
  '/docs/content-management-api/resources/upload',
  '/docs/content-management-api/resources/upload-request',
  '/docs/content-management-api/resources/upload-track',
  '/docs/content-management-api/resources/scheduled-publication',
  '/docs/content-management-api/resources/scheduled-unpublishing',
  '/docs/content-management-api/resources/search-result',
  '/docs/content-management-api/resources/environment',
  '/docs/content-management-api/resources/maintenance-mode',
  '/docs/content-management-api/resources/webhook',
  '/docs/content-management-api/resources/webhook-call',
  '/docs/content-management-api/resources/build-trigger',
  '/docs/content-management-api/resources/item-type-filter',
  '/docs/content-management-api/resources/upload-filter',
  '/docs/content-management-api/resources/site-invitation',
  '/docs/content-management-api/resources/editing-session',
  '/docs/content-management-api/resources/form-data',
  '/docs/content-management-api/resources/sso-group',
  '/docs/content-management-api/resources/sso-settings',
  '/docs/content-management-api/resources/emoji-suggestions',
  '/docs/content-management-api/resources/white-label-settings',
  '/docs/content-management-api/resources/public-info',
  '/docs/content-management-api/resources/daily-usage',
  '/docs/content-management-api/resources/usage-counter',
  '/docs/content-management-api/resources/upload-tag',
  '/docs/content-management-api/resources/upload-smart-tag',
  '/docs/content-management-api/resources/site',
  '/docs/content-management-api/resources/workflow',
];

export type FinderResult = Promise<
  [string, string] | 'ITEM_NOT_FOUND' | 'INVALID_ROUTE' | 'MULTIPLE_ITEMS'
>;

function finderByModelField(urlParam: string, modelApiKey: string, fieldApiKey: string) {
  return async (
    client: Client,
    params: Partial<Record<string, string | string[]>>,
  ): Promise<FinderResult> => {
    const fieldValue = params[urlParam];
    const { data: items } = await client.items.rawList({
      filter: {
        type: modelApiKey,
        fields: {
          [fieldApiKey]: { eq: Array.isArray(fieldValue) ? fieldValue.join('/') : fieldValue },
        },
      },
    });
    if (items.length > 1) {
      return 'MULTIPLE_ITEMS';
    }
    const firstItem = items[0];
    if (!firstItem) {
      return 'ITEM_NOT_FOUND';
    }
    return [modelApiKey, firstItem.id];
  };
}

export const itemFinders = [
  {
    pattern: '/academy/:courseSlug/:chapterSlug',
    finder: finderByModelField('chapterSlug', 'academy_chapter', 'slug'),
  },
  {
    pattern: '/academy/:courseSlug',
    finder: finderByModelField('courseSlug', 'academy_course', 'slug'),
  },
  {
    pattern: '/blog/:slug',
    finder: finderByModelField('slug', 'blog_post', 'slug'),
  },
  {
    pattern: '/product-updates/:slug',
    finder: finderByModelField('slug', 'changelog_entry', 'slug'),
  },
  {
    pattern: '/customer-stories/:slug',
    finder: finderByModelField('slug', 'customer_story', 'slug'),
  },
  {
    pattern: '/docs/:docGroupSlug/:pageSlug',
    finder: async (
      client: Client,
      params: Partial<Record<string, string | string[]>>,
    ): Promise<FinderResult> => {
      const { pageSlug, docGroupSlug } = params;
      let { data: possibleDocPages } = await client.items.rawList({
        filter: { type: 'doc_page', fields: { slug: { eq: pageSlug } } },
      });

      const matchingDocPages: SchemaTypes.Item[] = [];
      for (const docPage of possibleDocPages) {
        const docGroups = await client.items.references(docPage, { version: 'published' });
        if (docGroups.find((docGroup) => docGroup.slug === docGroupSlug)) {
          matchingDocPages.push(docPage);
        }
      }

      if (matchingDocPages.length > 1) {
        return 'MULTIPLE_ITEMS';
      }

      const firstItem = matchingDocPages[0];

      if (!firstItem) {
        return 'ITEM_NOT_FOUND';
      }

      return ['doc_page', firstItem.id];
    },
  },
  {
    pattern: '/docs/:docGroupSlug',
    finder: finderByModelField('docGroupSlug', 'doc_group', 'slug'),
  },
  {
    pattern: '/marketplace/enterprise/:slug',
    finder: finderByModelField('slug', 'enterprise_app', 'slug'),
  },
  {
    pattern: '/features/:slug',
    finder: finderByModelField('slug', 'feature', 'slug'),
  },
  {
    pattern: '/marketplace/hosting/:slug',
    finder: finderByModelField('slug', 'hosting_app', 'slug'),
  },
  {
    pattern: '/cms/:slug',
    finder: finderByModelField('slug', 'landing_page', 'slug'),
  },
  {
    pattern: '/partners/:slug',
    finder: finderByModelField('slug', 'partner', 'slug'),
  },
  {
    pattern: '/marketplace/plugins/i/*packageName',
    finder: finderByModelField('packageName', 'plugin', 'package_name'),
  },
  {
    pattern: '/compare/:slug',
    finder: finderByModelField('slug', 'product_comparison', 'slug'),
  },
  {
    pattern: '/marketplace/starters/:code',
    finder: finderByModelField('code', 'template_demo', 'code'),
  },
  {
    pattern: '/use-cases/:slug',
    finder: finderByModelField('slug', 'use_case_page', 'slug'),
  },
  {
    pattern: '/user-guides/:chapterSlug/:episodeSlug',
    finder: finderByModelField('episodeSlug', 'user_guides_episode', 'slug'),
  },
  {
    pattern: '/partners/:partnerSlug/showcase/:projectSlug',
    finder: finderByModelField('projectSlug', 'showcase_project', 'slug'),
  },
  {
    pattern: '/customers/:slug',
    finder: finderByModelField('slug', 'success_story', 'slug'),
  },
  {
    pattern: '/tech-partners/:slug',
    finder: finderByModelField('slug', 'tech_partner', 'slug'),
  },
];

export const redirects = Object.entries({
  '/marketplace/plugins/i/datocms-plugin-yoast-seo':
    '/marketplace/plugins/i/datocms-plugin-seo-readability-analysis',
  '/docs/introduction/custom-assets-domain': '/marketplace/enterprise/aws-s3',
  '/search': '/docs/site-search',
  '/docs/search': '/docs/site-search',
  '/about': '/company/about',
  '/brand-assets': '/company/brand-assets',
  '/docs/building-plugins/*splat': '/docs/legacy-plugins/*splat',
  '/docs/guides/custom-assets-domain/*splat': '/marketplace/enterprise/*splat',
  '/docs/guides/single-sign-on': '/marketplace/enterprise',
  '/docs/guides/single-sign-on/configure-sso-with-okta': '/marketplace/enterprise/okta-sso',
  '/docs/guides/single-sign-on/configure-sso-with-onelogin': '/marketplace/enterprise/onelogin-sso',
  '/docs/deployments/travis': '/marketplace/hosting/travis-ci',
  '/docs/deployments/*splat': '/marketplace/hosting/*splat',
  '/plugins/i/@stackbitdatocms-plugin-typed-list':
    '/marketplace/plugins/i/@stackbit/datocms-plugin-typed-list',
  '/plugins/i/@ecologicdatocms-plugin-multiselect':
    '/marketplace/plugins/i/@ecologic/datocms-plugin-multiselect',
  '/plugins/i/@ecologicdatocms-plugin-ordered-tag-editor':
    '/marketplace/plugins/i/@ecologic/datocms-plugin-ordered-tag-editor',
  '/content-management-api': '/docs/content-management-api',
  '/plugins': '/marketplace/plugins',
  '/plugins/i/*splat': '/marketplace/plugins/i/*splat',
  '/docs/plugins/entry-point': '/docs/building-plugins/entry-point',
  '/docs/plugins/creating-a-new-plugin': '/docs/building-plugins/creating-a-new-plugin',
  '/docs/plugins/publishing': '/docs/building-plugins/publishing',
  '/docs/guides/offline-backups': '/docs/import-and-export/export-data',
  '/docs/general-concepts/transfer': '/docs/plans-pricing-and-billing/transfer',
  '/docs/content-management-api/js-client': '/docs/content-management-api/using-the-nodejs-clients',
  '/docs/security': '/security',
  '/docs/guides/private-videos': '/docs/content-modelling/external-video-field',
  '/docs/content-delivery-api/overview': '/docs/content-delivery-api',
  '/docs/content-delivery-api/endpoint': '/docs/content-delivery-api/api-endpoints',
  '/docs/content-delivery-api/complexity_limiting': '/docs/content-delivery-api/complexity',
  '/docs/content-delivery-api/first-request': '/docs/content-delivery-api/your-first-request',
  '/docs/content-delivery-api/querying': '/docs/content-delivery-api/how-to-fetch-records',
  '/docs/content-delivery-api/filtering': '/docs/content-delivery-api/filtering-records',
  '/docs/content-delivery-api/ordering': '/docs/content-delivery-api/ordering-records',
  '/docs/content-delivery-api/modular-content': '/docs/content-delivery-api/modular-content-fields',
  '/docs/content-delivery-api/uploads': '/docs/content-delivery-api/images-and-videos',
  '/docs/content-delivery-api/seo': '/docs/content-delivery-api/seo-and-favicon',
  '/blog/2': '/blog/p/2',
  '/changelog/2': '/product-updates/p/2',
  '/changelog/3': '/product-updates/p/3',
  '/changelog/4': '/product-updates/p/4',
  '/changelog/5': '/product-updates/p/5',
  '/changelog/6': '/product-updates/p/5',
  '/changelog/*splat': '/product-updates/*splat',
  '/docs/general-concepts/pricing': '/docs/plans-pricing-and-billing',
  '/docs/guides/installing-site-search/*splat': '/docs/site-search/*splat',
  '/docs/guides/*splat': '/docs/*splat',
  '/docs/static-generators/gatsbyjs/*splat': '/docs/gatsby/*splat',
  '/docs/static-generators/*splat': '/docs/*splat',
  '/docs/single-page-apps/*splat': '/docs/*splat',
  '/marketplace/hosting/zeit': '/marketplace/hosting/vercel',
  '/cms/react': '/cms/react-cms',
  '/cms/hugo': '/cms/hugo-cms',
  '/cms/nextjs': '/cms/nextjs-cms',
  '/cms/nuxt-js': '/cms/nuxtjs-cms',
  '/cms/jekyll': '/cms/jekyll-cms',
  '/cms/middleman': '/cms/middleman-cms',
  '/cms/vue': '/cms/vue-js-cms',
  '/cms/gatsbyjs': '/cms/gatsbyjs-cms',
  '/features/video-streaming-encoding': '/features/video-api',
  '/features/graphql-content-api': '/features/headless-cms-graphql',
  '/features/multi-language': '/features/headless-cms-multi-language',
  '/features/workflows': '/features/workflow-cms',
  '/features/real-time': '/features/real-time-api',
  '/features/structured-text': '/features/structured-content-cms',
  '/made-for/digital-marketers': '/made-for/cms-digital-marketing',
  '/blog/what-is-an-headless-cms': '/blog/what-is-a-headless-cms',
  '/made-for/developers': '/made-for/best-cms-for-developers',
  '/enterprise': '/enterprise-headless-cms',
  '/marketplace/starters/nextjs-blog': '/marketplace/starters/nextjs-template-blog',
  '/blog/offer-responsive-progressive-lqip-images-in-2020':
    '/blog/best-way-for-handling-react-images',
  '/blog/static-ecommerce-website-snipcart-gatsbyjs-datocms': '/blog/gatsby-ecommerce-tutorial',
  '/cms/gatsbyjs-cms': '/cms/gatsby-cms',
  '/legal/security': '/security',
  '/legal/privacy': '/legal/privacy-policy',
  '/docs/pro-tips/manage-draft-published-state-by-locale':
    '/docs/general-concepts/localization#locale-based-publishing',
  '/marketplace/starters/next-js-multilingual-blog-per-local-publishing':
    '/docs/general-concepts/localization#locale-based-publishing',
  '/pricing/compare': '/pricing',
  '/docs/content-management-api/rate-limits': '/docs/content-management-api/technical-limits',
  '/docs/content-delivery-api/rate-limiting': '/docs/content-delivery-api/technical-limits',
  '/partners/locale': '/tech-partners/crowdin',
  '/partners/imgix': '/tech-partners/imgix',
  '/blog/introducing-visual-editing-for-vercel-and-datocms-enterprise-customers':
    '/blog/introducing-content-link-for-vercel-and-datocms-enterprise-customers',
  '/blog/july-update-visual-editing-and-per-locale-publishing':
    '/blog/july-update-content-link-and-per-locale-publishing',
  '/docs/visual-editing': '/docs/content-link/how-to-use-content-link',
  '/docs/visual-editing/how-to-use-visual-editing': '/docs/content-link/how-to-use-content-link',
  '/partners/harvey-cameron/showcase/jacuzzi ': '/partners',
  '/docs/plugins/install': '/docs/general-concepts/plugins',
  '/blog/live-preview-changes-on-gatsby-preview': '/blog',
  '/docs/localizing-images': '/docs/content-delivery-api/images-and-videos',
  '/cda-explorer': '/docs/content-delivery-api',
  '/docs/content-management-api/using-the-ruby-client': '/docs/content-management-api',
  '/use-cases': '/',
  '/docs/cdn-settings/advanced-asset-settings': '/docs/asset-api/asset-cdn-settings',
  '/docs/general-concepts/videos': '/docs/asset-api/videos',
  '/docs/general-concepts/images': '/docs/asset-api/images',
  '/docs/project-starters-and-templates': '/docs/general-concepts/project-starters-and-templates',
  '/docs/project-starters-and-templates/clone-project-button':
    '/docs/general-concepts/project-starters-and-templates#generate-a-clone-project-button',
  '/docs/project-starters-and-templates/project-starter-button':
    '/docs/general-concepts/project-starters-and-templates#generate-a-project-starter-button',
  '/blog/headless-cms-unconventional-use-cases': '/customer-stories/trip-to-japan',
  '/docs/plugin-sdk': '/docs/plugin-sdk/introduction',
  '/docs/general-concepts/environments': '/docs/general-concepts/primary-and-sandbox-environments',
  '/docs/react/*splat': '/docs/next-js/*splat',
  '/marketplace/plugins/i/datocms-plugin-gatsby-cloud': '/',
  '/docs/content-management-api/resources/sso-token':
    '/docs/content-management-api/resources/sso-settings/generate_token',
  '/docs/next-js/setting-up-next-js-preview-mode':
    '/docs/legacy-next-js-documentation/setting-up-next-js-preview-mode',
  '/docs/plugin-sdk/execute-code-on-boot': '/docs/plugin-sdk/event-hooks',
  '/partners/harvey-cameron': '/partners',
  '/docs/vue/display-videos': '/docs/nuxt',
  '/docs/vue/loading-responsive-progressive-images-from-datocms': '/docs/nuxt',
  '/docs/vue': '/docs/nuxt',
  '/docs/vue/*splat': '/docs/nuxt/*splat',
  '/docs/sveltekit/getting-started-with-sveltekit-and-datocms': '/docs/svelte',
  '/partners/dev-kitchen': '/partners',
  '/docs/plugin-sdk/sdk/field-extensions ': '/docs/plugin-sdk/field-extensions',
  '/cms/hugo-cms': '/',
  '/marketplace/starters/next-13-company-landing-page-demo':
    '/marketplace/starters/next-js-starter-kit',
  '/docs/agency-partner-program/benefits': '/partner-program',
  '/docs/site-search/excluding-text':
    '/docs/site-search/how-the-crawling-works#excluding-content-from-indexing',
  '/docs/building-plugins/creating-a-new-plugin': '/docs/plugin-sdk/introduction',
  '/docs/building-plugins/sdk-reference': '/docs/plugin-sdk/introduction',
  '/docs/building-plugins/entry-point': '/docs/plugin-sdk/introduction',
  '/docs/gatsby': '/docs',
  '/docs/other-ssgs': '/docs',
  '/docs/guides/building-plugins/sdk-reference': '/docs/plugin-sdk/build-your-first-plugin',
  '/docs/react': '/docs',
  '/docs/guides/building-plugins/creating-a-new-plugin': '/docs/plugin-sdk/build-your-first-plugin',
  '/docs/hugo': '/docs',
  '/docs/building-plugins': '/docs/plugin-sdk/build-your-first-plugin',
  '/docs/building-plugins/using-the-generator': '/docs/plugin-sdk/build-your-first-plugin',
  '/docs/content-delivery-api/docs/general-concepts/roles-and-permission-system':
    '/docs/general-concepts/roles-and-permission-system',
  '/docs/plugin-sdk/render%E2%80%8BUpload%E2%80%8BSidebarPanel': '/docs/plugin-sdk/sidebar-panels',
  '/docs/plugin-sdk/sdk/field-extensions': '/docs/plugin-sdk/field-extensions',
  '/docs/building-plugins/install':
    '/docs/plugin-sdk/build-your-first-plugin#install-your-plugin-in-the-datocms-web-app',
  '/docs/building-plugins/publishing': '/docs/plugin-sdk/publishing-to-marketplace',
  '/docs/guides': '/docs',
  '/docs/react/managing-images': '/docs',
  '/marketplace/plugins/i/git@github.com:voorhoede/datocms-plugin-editor-help.git':
    '/marketplace/plugins',
  '/marketplace/plugins/i/license': '/marketplace/plugins',
  '/docs/gatsby/gatsby-cloud': '/docs',
  '/docs/single-page-apps/react': '/docs',
  '/docs/static-generators/gatsbyjs': '/docs',
  '/marketplace/plugins/i/contributing.md': '/docs/plugin-sdk/publishing-to-marketplace',
  '/marketplace/starters/middleman-portfolio': '/marketplace/starters',
  '/docs/react/structured-text-fields': '/docs',
  '/marketplace/plugins/i/LICENSE.txt': '/docs/plugin-sdk/publishing-to-marketplace',
  '/docs/middleman': '/docs',
  '/docs/guides/localizing-images': '/docs/asset-api/images',
  '/blog/introducing-inherited-roles-for-greater-modularity-in-role-management':
    '/blog/introducing-inherited-roles',
  '/marketplace/plugins/i/datocms-plugin-kontainer': '/marketplace/plugins',
  '/docs/vue/rendering-structured-text-fields': '/docs/nuxt/rendering-structured-text-fields',
  '/product-updates/undefined': '/product-updates',
  '/docs/content-management-api/resources/item/instances/docs/content-management-api/resources/item/instances':
    '/docs/content-management-api',
  '/marketplace/starters/next-js-multilingual-blog': '/marketplace/starters',
  '/docs/guides/installing-site-search/widget': '/docs/general-concepts/site-search',
  '/docs/pro-tips/create-a-select-with-a-single-line-string-field': '/docs',
  '/docs/guides/building-plugins': '/docs/plugin-sdk/build-your-first-plugin',
  '/partners/tecnica': '/partners',
  '/docs/hugo/fields': '/docs',
  '/docs/content-modelling/data-migration/docs/content-modelling/data-migration':
    '/docs/content-modelling/data-migration',
  '/partners/harvey-cameron/showcase/jacuzzi': '/partners',
  '/docs/plugin-sdk/field-extension': '/docs/plugin-sdk/field-extensions',
  '/docs/jekyll/fields': '/docs',
  '/docs/static-generators/middleman/image-manipulation': '/docs',
  '/docs/gatsby/examples': '/docs',
  '/docs/guides/custom-assets-domain/google-cloud-storage':
    '/marketplace/enterprise/google-cloud-storage',
  '/use-cases/docs': '/use-cases/headless-cms-knowledge-management',
  '/features/headless-cms-multi-languag': '/features/headless-cms-multi-language',
  '/docs/guides/custom-assets-domain': '/docs',
  '/docs/deployments/zeit': '/docs',
  '/docs/content-management-api/resources/upload/updatebut':
    '/docs/content-management-api/resources/upload',
  '/foo': '/docs',
}).map(([pattern, replacement]) => ({
  matcher: match(pattern, { decode: decodeURIComponent }),
  replacer: (params: Partial<Record<string, string | string[]>>) =>
    replacement.replace('*splat', params?.splat ? (params.splat as string[]).join('/') : '*SPLAT'),
}));
