proxy:
  hosts:
    - www.staging-datocms.com
    - www-draft.staging-datocms.com

env:
  clear:
    DRAFT_MODE_HOSTNAME: www-draft.staging-datocms.com
    DEPLOYMENT_DESTINATION: staging

builder:
  args:
    PUBLIC_HOSTNAME: www.staging-datocms.com
